### ISSUE TITLE
Release 3.4.4: tarballs missing 

### ISSUE THREAD

**Issue by nilason** [LASzip/LASzip#105]
Thanks for the release! The tarballs and friends (`laszip-src-3.4.4.tar.[bz2|gz].*`) are missing though.

**Comment by thbeu** [comment]
FYI: Laszip 3.4.4 is available via Conan now: https://conan.io/center/recipes/laszip?version=3.4.4

**Comment by rapidlasso** [comment]
Thanks @thbeu !

**Comment by thbeu** [comment]
Oops, sorry. These are two orthogonal issues: The tarballs are still missing at https://github.com/LASzip/LASzip/releases/tag/3.4.4 (while being available for https://github.com/LASzip/LASzip/releases/tag/3.4.3).

**Comment by nilason** [comment]
@rapidlasso Please reopen this issue, the tarballs are still missing.

**Comment by rapidlasso** [comment]
tarball created by
    git archive --format=tar.gz -o ../laszip-src-3.4.4.tar.gz --prefix=laszip-src-3.4.4.tar.gz/ 3.4.4
and added to the release

**Comment by nilason** [comment]
Thanks!
