### ISSUE TITLE
A new release ?

### ISSUE THREAD

**Issue by tigerfoot** [LASzip/LASzip#13]
since the number of changes accumulate over time now in master, isn't the right time to got a new release ?

**Comment by tigerfoot** [comment]
ping ? :-)

**Comment by hobu** [comment]
@rapidlasso is currently implementing full LAZ 1.4 support. We will provide a beta release of that once it is ready.

**Comment by rapidlasso** [comment]
Soon. Quantum Spatial is evaluating the latest feature right now.

**Comment by tigerfoot** [comment]
Excellent news.

**Comment by maruncz** [comment]
any new news about release?

master is not compatible with liblas and last release requires to cherry-pick one commit from master to be compatible

https://github.com/libLAS/libLAS/issues/58

**Comment by hobu** [comment]
There won't be a release until LAZ 1.4 is complete. libLAS and any other software depending on LASzip should be using official LASzip releases, not master.

**Comment by rapidlasso** [comment]
I expect the native extension of LASzip to LAS 1.4 to be completed this
fall. If you want to review and provide input or feedback on current design
choices please look for the relevant github links in "the LAS room" on

http://groups.google.com/group/lasroom

Regards,

Martin
