### ISSUE TITLE
./autogen.sh not mentioned in install instructions

### ISSUE THREAD

**Issue by SHOTbyGUN** [LASzip/LASzip#17]
https://github.com/LASzip/LASzip/blob/master/INSTALL

should have "./autogen" as first step, since configure file does not exist if cloned from git.

**Comment by hobu** [comment]
That's a default INSTALL file from gnu. `autogen.sh` is not standard, but it does exist by convention.

We do not maintain autogenerated output inside of the source tree for easy merge and file tracking.
