### ISSUE TITLE
Latest commits do not work with liblas

### ISSUE THREAD

**Issue by codegrafix** [LASzip/LASzip#19]
Hi!
I have problems getting your latest version running with the latest liblas lib.
As I have seen,  in the include directory no headers will be provided for a non-static build.
On this hash everything works normal: 1c0ed13caf005d318759b5deafee9386d928429c.

In my project, both repos are included with cmake externalproject_add():
# LASzip

```
externalproject_add(
       ep_LASzip
       GIT_REPOSITORY "LASzip.git"
       UPDATE_COMMAND ""
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DCMAKE_BUILD_TYPE=Release
)
```
# LibLAS

```
externalproject_add(
       ep_liblas
       GIT_REPOSITORY "libLAS"
       UPDATE_COMMAND ""
       INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
       CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DWITH_LASZIP=TRUE -DLASZIP_INCLUDE_DIR=${CMAKE_INSTALL_PREFIX}/include -DCMAKE_BUILD_TYPE=Release
)
```

If you have any question please let me know.

I would be please If you could find the problem and give me a working solution.

Best regards
Patrick

**Comment by hobu** [comment]
The master branch is currently in flux as we update in preparation for LAZ 1.4 implementation. Please stick to released versions of LASzip with libLAS and PDAL at this time.

**Comment by hobu** [comment]
libLAS requires LASzip 2.8 or lower at this time. libLAS has not been updated to support either LAS 1.4 or LAZ 1.4 with LASzip 3.0.0+
