### ISSUE TITLE
Visual Studio 2013/2015 build errors (unordered_map)

### ISSUE THREAD

**Issue by ollira** [LASzip/LASzip#23]
CMake sets -DUNORDERED option for compilers. Two source files use it in ifdefs: lasindex.cpp and lasinterval.cpp.

Visual Studio 2013 and 2015 builds stop at the include statement inside the ifdef:
    #include <tr1/unordered_map>

Build commands:
    mkdir vs2015-x64
    cd vs2015-x64
    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    nmake

Error message:
    C:\or\src\LASzip\src\lasindex.cpp(53) : fatal error C1083: Cannot open include file: 'tr1/unordered_map': No such file or directory

Visual Studio can compile this code:
    #include <unordered_map>
    using std::unordered_map;

Regards,
Olli Räisä

**Comment by abellgithub** [comment]
This seems to have been addressed.
