### ISSUE TITLE
Configure error: cannot find install-sh, install.sh ...

### ISSUE THREAD

**Issue by themmes** [LASzip/LASzip#25]
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

Trying to run configure, installed autoconf.

```
hemmest@pc:/LASzip$ autoconf
configure.ac:31: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:37: error: possibly undefined macro: AC_PROG_LIBTOOL
```

Running `./configure` results in not being able to find the installation bash script

`configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."`

What am I doing wrong here?

**Comment by themmes** [comment]
Status is as follows, I tried to download from source at http://www.laszip.org/ (the 2013-08-05 .tar.gz). This version does actually contain a `.configure`. When running `make` and `make install` no error messages, so all seems good. However, the application does not run;

```
hemmest@pc:/laszip-src-2.2.0# laszip
bash: laszip: command not found
```

**Comment by hobu** [comment]
This is the developer's library for providing LAZ support to applications, not the command-line application for transforming data. The `laszip` utility you seek is part of LAStools.
