### ISSUE TITLE
undefined symbol: laszip_create

### ISSUE THREAD

**Issue by ahmadshabbir2468** [LASzip/LASzip#29]
Hi,
I try to install laszip with potree but suddenly it give me this Error and Every thing is stuck 
Please Guide 

symbol lookup error: PotreeConverter: undefined symbol: laszip_create

Either it is Some Variable Or something else

**Comment by rapidlasso** [comment]
I think this may need to be debugged on the other end. Look at the potree github site

https://github.com/potree/potree
