### ISSUE TITLE
laszip_api_version.h omitted from package

### ISSUE THREAD

**Issue by tomvantilburg** [LASzip/LASzip#30]
I have limited cmake knowledge but it appears that the `laszip_api_version.h` is intentionally left out of the package by this line:

https://github.com/LASzip/LASzip/blob/f3bc2fc1e8492b348b4a077c87334c9330b6fc07/cmake/cpack.cmake#L42

PDAL(trunk) is expecting to find it though:
https://github.com/PDAL/PDAL/commit/298a09a4f2913a9fc5c7f763ac2ba9aeb42df449

It seems this file is wrongfully excluded from the laszip installation?

**Comment by hobu** [comment]
This is a bug. A new 3.1.1 release will be made to correct it.

**Comment by hobu** [comment]
https://github.com/LASzip/LASzip/releases/tag/3.1.1 should have it fixed.

**Comment by tomvantilburg** [comment]
Works for me. thx.
