### ISSUE TITLE
Why did library version number decrease?

### ISSUE THREAD

**Issue by ryandesign** [LASzip/LASzip#36]
Hi, I'm a developer with MacPorts. We're working on [updating our LASzip port](https://trac.macports.org/ticket/55346) from version 2.2.0 to 3.1.1. I noticed that LASzip 2.2.0 provides library version 6:

```
$ port -q installed LASzip and active
  LASzip @2.2.0_0 (active)
$ otool -L /opt/local/lib/liblaszip.dylib
/opt/local/lib/liblaszip.dylib:
	/opt/local/lib/liblaszip.6.0.0.dylib (compatibility version 6.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
$
```

while LASzip 3.1.1 provides library version 3:

```
$ port -q installed LASzip and active
  LASzip @3.1.1_0 (active)
$ otool -L /opt/local/lib/liblaszip.dylib
/opt/local/lib/liblaszip.dylib:
	/opt/local/lib/liblaszip.3.dylib (compatibility version 3.0.0, current version 3.1.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
$
```

Why did the library version number decrease? Shouldn't library version numbers only ever increase?

**Comment by hobu** [comment]
This is a bug. The 2.x version of LASzip didn't really have explicit SOVERSION naming, and I think I tried to set it straight to follow libLAS, PDAL, and others, and I didn't realize that we already had a naming convention going.

I can issue a new release to fix this issue. Presumably we need `7.0.0` because LASzip 3.x completely changed the public interface to LASzip. Applications written against the 2.x API (most notably libLAS) will need to be updated to catch up to it.

Sorry for the churn.

**Comment by rapidlasso** [comment]
There was not really a big interface change as far as current users are concerned ... unless you want to add support to write LAS 1.4. I can drop the new DLL into places where the old DLL was (like for FUSION) and my old FUSION install can suddenly read native compressed LAS 1.4 content (obviously without scanner channel or selective decompression).

**Comment by ryandesign** [comment]
What's the status of getting the library versioning fixed? I don't see any new commits...

**Comment by hobu** [comment]
There is an issue with how the current version of LASzip writes data in specific circumstances which will necessitate a new major version. We were trying to get that sorted and then we will fix up the SOVERSION stuff at the same time.

**Comment by hobu** [comment]
ok, SOVERSION stuff is now simply the library version. This doesn't follow libtool versioning though.

**Comment by ryandesign** [comment]
Looks like LASzip 3.2.0 was released, still having library major version 3.

**Comment by rapidlasso** [comment]
Yep. Give it six to twelve more months or so and we'll release LASzip 4.0.0. There is a new set of decompressors in the LASzip 3.2.0 release for the new LAS 1.4 point types. Once the LASzip 3.2.0 version has "percolated" into enough software packages we will make a LASzip 4.0.0 release where also the new set of compressors is activated. The delay is to maximize the number of software packages that are ready for the new compression schemes.

**Comment by hobu** [comment]
> Looks like LASzip 3.2.0 was released, still having library major version 3.

I'll make a 3.2.1 to fix this. God I hate libtool.

**Comment by hobu** [comment]
For 3.2.1, I am setting the version to `8.0.0` and for 4.0+ it will be `9.0.0` to follow the older libtool versioning that was done. Sorry for the churn here.

**Comment by hobu** [comment]
3.2.1 released. Please let me know if you still have issues.

https://github.com/LASzip/LASzip/releases/tag/3.2.1
