### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by hrsantiago** [LASzip/LASzip#37]
Hello, I was attempting to read points inside multiple rects (one at a time), but laszip crashed at this line.
Length is 0 so there was a division by 0.

I'm not sure what's the correct behaviour in order to fix this. Maybe this function shouldn't be called when length is 0.

Edit: It might be helpful to know that the last error is:
end-of-file during chunk with index 2802

Here's a backtrace and variables.

![image](https://user-images.githubusercontent.com/609897/33453627-7f697922-d5fd-11e7-8bc1-61cf68d4f21a.png)

**Comment by rapidlasso** [comment]
This could have a million different reasons, the most likely being (I'm probably just being lazy (-:) a memory override on your end. The Arithmetic stuff is not really part of the LASzip magic but LASzip just uses the FastAC range-coding wizardry of some other bit joggler.

**Comment by hobu** [comment]
Closing until the issue is more clearly demonstrated.
