### ISSUE TITLE
LAStools/LAStools/LASzip differs from LASzip/LASzip

### ISSUE THREAD

**Issue by alexd2580** [LASzip/LASzip#42]
I'm trying to write a small .laz compatible application with the use of LASzip. However when I tried compressing LAS1.4 the same way that `LAStools/bin/laszip` does it failed at the second point, not writing anything to the stream. `LAStools/lasinfo` and `QTreader` both complained about broken `.laz`. When i continued investigating the problem I found that the `LASzip/LASzip` and `LAStools/LAStools/LASzip` repositories are not the same.

When trying to compress LAS1.4 with `LAStools/bin/laszip` i get a nice 1.4 LAZ.

Now I'm stuck trying to make it compile with the version from `LAStools/LAStools/LASzip`, however, it does not have a CMakefile which integrates nicely into my project and worked like a charm in `LASzip/LASzip`.

Which of these repositories should I use if I just want to have a `laswriter.hpp` which can write 1.2LAZ/1.4LAZ (without the compatibility mode)?

**Comment by rapidlasso** [comment]
The LASwriter or the LASwriteOpener are both parts of LASlib, not of LASzip. The (much larger) LASlib library that also contains filters, transforms, and converters fully integrates the LASzip library. But to use the LASzip library only you need to go via the laszip_api.h functions as documented via many examples in the laszipdllexample.cpp example code. Note that LASlib now also has a nice CMakefile ... (-: 

Please note, however, that there is no "static linking exception" for LASlib like there is for LASzip.
