### ISSUE TITLE
laszip.hpp no longer installed?

### ISSUE THREAD

**Issue by paulmelis** [LASzip/LASzip#48]
[liblas](https://liblas.org/) no longer builds against laszip 3.x as it uses `laszip.hpp`, which no longer seems to be installed as of 3.x. Is `laszip.hpp` part of the official API for laszip? The `laszippertest` example seems to use it through `laszipper.h` (the latter might also be a nice high-level API for certain uses of laszip).

**Comment by hobu** [comment]
> liblas no longer builds against laszip 3.x as it uses laszip.hpp

This is libLAS' problem. It needs an update to catch up to the LASzip 3.x API.  The API that libLAS used was completely deprecated.
