### ISSUE TITLE
Empty download files for 3.3.1

### ISSUE THREAD

**Issue by brechtsanders** [LASzip/LASzip#54]
The download asset files for version 3.3.1 (on https://github.com/LASzip/LASzip/releases) seem empty (archive files are < 70 bytes).

**Comment by drhpc** [comment]
Confirm. I am using an older release for now in pkgsrc. I need stable upstream tarballs … please provide a re-release.

**Comment by hobu** [comment]
3.3.1 release updated with fixed tarballs.
