### ISSUE TITLE
FastAC code (to be) relicensed under the BSD-2-Clause license

### ISSUE THREAD

**Issue by sebastic** [LASzip/LASzip#55]
Thanks for Tom "spot" Callaway of RedHat for Fedora Legal, the FastAC authors have agreed to relicense their code under the BSD-2-Clause license, see the attachments in the Bugzilla issue:

 [Bug 1674537 - LASzip contains FastAC code which does not allow modification](https://bugzilla.redhat.com/show_bug.cgi?id=1674537)

Direct links:

 * [BSD_Relicense_of_FastAC_code.pdf](https://bugzilla.redhat.com/attachment.cgi?id=1549115)
   Contains the email thread between Tom Callaway, Amir Said & William (Bill) Pearlman
 * [new-fastac-header.txt](https://bugzilla.redhat.com/attachment.cgi?id=1549116)
  The updated license header for the FastAC code

There is no new release of the FastAC code yet, once that's available the license issue preventing distributions from distributing LASzip should be resolved.

**Comment by rapidlasso** [comment]
This is awesome. Sorry I was not more proactive on that issue. But really glad to see it resolved!!! (-:

**Comment by sebastic** [comment]
It took almost 5 years and two distributions to get the FastAC license issue resolved, but I think we can close this issue with the changes in 3.4.0.

**Comment by spotrh** [comment]
Upstream pushed a new zip file with FastAC relicensed:
http://ecse.rpi.edu/~pearlman/SPIHT/EW_Code/FastAC_fix-nh.zip
