### ISSUE TITLE
Indexed LAZ reading performance

### ISSUE THREAD

**Issue by Grepsy** [LASzip/LASzip#61]
Hi, 

I hope this is the right place to ask these questions, please let me know if not.

We're developing a webservice to serve small areas from large pointclouds stored as LAZ-files. We're looking into ways to speed up the process of clipping and serving the pointcloud data. The datasets consists of country-wide LIDAR tiles stored as LAZ, indexed using `lasindex`. An example would be the Dutch AHN3 pointcloud (~2 TB of tiled data). Our requests usually are an area of ~50x50m.

What we've tried so-far:

- using `las2txt` directly, capturing `stdout`
- interop with LASzip (we're using .NET) to fetch the points (about 20% faster then above)
- reading from multiple sources in parallel (different acquisition years)

We would like to use the LASzip approach in parallel, but run into problems with multi-threading. It seems we can't use LASzip in a thread-safe manner. When using LASzip from multiple threads we get unpredictable results. Is this expected?

Current results for fetching a 50x50 ~1200ms/req for a 50x50m area using las2txt, and ~1000ms/req for LASzip.

We're looking to improve these numbers and would be thrilled to get any suggestions!

**Comment by rapidlasso** [comment]
There is no multi-threading support in LASzip at the moment. The biggest bang in terms of performance improvements are:

(1) if there are many tiles in one folder, don't use folder/*.laz as the input query (as laszip or las2txt will make a linear search over all files to check for bounding box overlap). instead create a light weight spatial data structure that stores all LAZ bounding boxes and LAZ file names and only give those tile to LASzip whose bounding box overlaps the area-of-interest query.

(2) make sure that the point order in each tile of the AHN3 point cloud is optimized for spatial queries, ideal orders for LiDAR strips are discussed [here ](https://rapidlasso.com/2014/08/19/preparing-raw-lidar-for-efficient-online-distribution/). For tiles try [lasoptimize](https://rapidlasso.com/lasoptimize/). The ideal point order is obtained with two sorts. The first sort optimizes for compression: sort points first by scanner channel, then by GPS time stamp, then by return number. The second sort takes the order from the first sort and puts a spatially coherent order on top with a 50 or 100 meter granularity. Within these 50 to 100 meter |buckets" the optimal compression order is retained. Such a sort makes lasindexed area-of-interest queries very efficient as fewer unneeded points require loading and decompression.

**Comment by Grepsy** [comment]
Thank you for the quick reply! Great information. 1 we're indeed already doing, 2 tried but ran into the issue that `lasoptimize64` could not handle the large tile size. Would it be possible to first split the individual tiles, then optimize, then merge again?

**Comment by rapidlasso** [comment]
There was a bug in [lasoptimize64](http://rapidlasso.com/lasoptimize/) that was [fixed a few days ago](http://lascloud.com/download/CHANGES.txt). Please let me know if the issues persist.

**Comment by Grepsy** [comment]
That worked well! We've also converted to LAS 1.4 and used selective decompression which yields another small perf. improvement. Closing this item.

Thank you for your help!
