### ISSUE TITLE
LICENSE fails to mention "static linking exception"

### ISSUE THREAD

**Issue by rapidlasso** [LASzip/LASzip#63]
The LASzip code is licensed LGPL 2.1 with the amendement that static linking is allowed if the code is not altered ("static linking exception"). This should be mentioned somewhere in the license statement.

**Comment by hobu** [comment]
After some research, I think we should consider relicensing LASzip to the [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/). People will know the ground rules under such a license. This will give people the ability to statically or dynamically link while still preserving the licensing characteristics we desire for the LASzip library in regards to reciprocality.

Adding our own static linking language to LGPLv2 (current LASzip license) has the potential to botch up things. Regardless of our intent, the language would matter. I haven't found any examples of standard language for the case we desire (LGPLv2.1 with static linking) that appears to have traction wide traction.

https://softwareengineering.stackexchange.com/questions/221365/mozilla-public-license-mpl-2-0-vs-lesser-gnu-general-public-license-lgpl-3-0

**Comment by rapidlasso** [comment]
Thanks for your research. I did not **really** want change license of LASzip because then it might complicate things on my end with the LASlib integration. We could maybe follow this model:

http://wiki.zeromq.org/area:licensing 

which I found via this discussion:

https://softwareengineering.stackexchange.com/questions/179084/is-there-a-modified-lgpl-license-that-allows-static-linking

and then I would simply add the required paragraph (see below) in all places where the LGPL 2.1 license is currently mentioned.

`**Static linking exception.** The copyright holders give you permission to link this library with independent modules to produce an executable, regardless of the license terms of these independent modules, and to copy and distribute the resulting executable under terms of your choice, provided that you also meet, for each linked independent module, the terms and conditions of the license of that module. An independent module is a module which is not derived from or based on this library. If you modify this library, you must extend this exception to your version of the library.`

But you may also have also come across the above link and therefore suggested to switch to the Mozilla Public License v2 as they also suggest ultimatively that in their article. 

Maybe I simply switch my LASlib stuff also to the Mozilla Public License v2 this would keep things just as simple. Can you think of any disadvantages to me (aka LASlib) in doing so in the long run?

**Comment by dg0yt** [comment]
IIUC the license was changed to Apache 2.0 with #80, and this issue becomes obsolete then. However it would be helpful to see the update license be part of an official release (tag), for reference in downstream packaging.
Thank you very much.

**Comment by hobu** [comment]
Yes, it would be good to have an official APL release, but there has not been much for updates to any code in years.

**Comment by nigels-com** [comment]
Yes a 3.5.0 release tag here on github would be helpful.  +1

**Comment by hobu** [comment]
@nigels-com this thread is out of date. We relicensed LASzip (and laz-perf) to Apache Public License 2 after Martin's death in 2022. See https://github.com/LASzip/LASzip/pull/80

**Comment by rapidlasso** [comment]
created new tag
