### ISSUE TITLE
Problems working with pcd file format

### ISSUE THREAD

**Issue by ChaturvediShilpa** [LASzip/LASzip#64]
Hi, 

I am working on lidar dataset from autonomous vechiles  such as nuscenes and apollo. They are in point cloud data (pcd.bin) format. 

Does laszip has an extension for pcd or it works on only las format ? Is there a standard converter for pcd to las ? 

Thanks

**Comment by rapidlasso** [comment]
LASzip only works on LAS and LAZ but maybe the PCD.bin contents can be fully mapped to LAS and LAZ via the concept of "additional attributes" or "extra bytes" available as of LAS 1.4. This is, however, not an issue with LASzip. Maybe inquire via the [LAStools user forum](https://groups.google.com/d/forum/lastools) for a solution.
