### ISSUE TITLE
Support for pcd bin 

### ISSUE THREAD

**Issue by ChaturvediShilpa** [LASzip/LASzip#66]
Hi team, 

Does LASZip supports pcd(point cloud data) format for compression ?

Thanks

**Comment by rapidlasso** [comment]
LASzip compresses LAS. But maybe a PCD pointcloud can be mapped to the LAS format? Maybe with the help of extra bytes? Like we can do it with the e57 format and or [the ASCII format](https://rapidlasso.com/2020/02/17/surprise-release-of-airborne-lidar-in-germanys-closed-data-state-bavaria/)? Then writing a pcd2las converter would be the correct way of going about,

**Comment by ChaturvediShilpa** [comment]
Does Laszip has restriction for 32 bit precision ? Is there a limit to the precision values for x, y and z. I am using PDAL library to convert my pcd data to laz data and I am seeing precion drop in the conversion process . 

Can Laszip handle any values for x, y and z or is it restricted to 32 bit int ?

**Comment by rapidlasso** [comment]
Then there is a bug in PDAL.

**Comment by hobu** [comment]
> I am seeing precion drop in the conversion process .

There is no bug in PDAL. This user does not follow the FAQ. We have linked to this in multiple issues, and they need to stop reaching out via support channels and follow the directions. https://pdal.io/tutorial/las.html#coordinate-scaling
