### ISSUE TITLE
Understanding the workflow

### ISSUE THREAD

**Issue by ChaturvediShilpa** [LASzip/LASzip#67]
Hi, 

I am trying to understand the workflow and algorithm. Can anyone please share some pointers.

Thanks

**Comment by pdappen** [comment]
Download the laszip.exe file here :http://lastools.org/download/laszip.exe
Running the .exe  will start a GUI interface.  
This video explains the process: https://www.youtube.com/watch?v=MoFtT5FBPXw&feature=youtu.be
It Starts at about the 5 minute mark.

**Comment by rapidlasso** [comment]
Thanks! There is also a paper and a video from the ELMF 2011 [available here](https://laszip.org/).
