### ISSUE TITLE
Debugging Code

### ISSUE THREAD

**Issue by ChaturvediShilpa** [LASzip/LASzip#68]
Hi, 

Can anyone share steps for setting this code for debugging on Visual Studio.

Thanks

**Comment by thbeu** [comment]
What did you try so far?

**Comment by thbeu** [comment]
Can this be closed?

**Comment by rapidlasso** [comment]
MSVS vcxproj files are included since a while, so debugging is easy possible in MSVS now, thanks @thbeu for the reminder
