### ISSUE TITLE
Using PDAL Laszip

### ISSUE THREAD

**Issue by ChaturvediShilpa** [LASzip/LASzip#70]
Hi, 

I am using PDAL libraries to convert pcd files to laz files but when I do reverse conversion from laz to pcd, there was loss in precision. 

Can anyone suggest, whether laszip does rounding off or loss of precision to achieve better compression or it is completely lossless ?

**Comment by hobu** [comment]
This is not a LASzip issue.

https://github.com/PDAL/PDAL/issues/3034#issuecomment-620656638
