### ISSUE TITLE
Inventory doesn't work in compatibility mode

### ISSUE THREAD

**Issue by AlienRenders** [LASzip/LASzip#72]
When closing the writer, the inventory doesn't update the 15 number of points per return because the LAS version has been changed to 1.2 or 1.3 in compatibility mode (and the point type has been changed to 1 for point type 6).

BTW, compatibility mode was the only way to store LAS 1.4 early on. I tried it without compatibility mode and it worked fine. Is there any reason for compatibility mode anymore? Is LAS 1.4 fully supported now? Also, where are the docs explaining the functions? I can't seem to find it.

**Comment by rapidlasso** [comment]
Sorry. This question is too cryptic. Details.

Details. Details. Details. Details. Details. Details.

**Comment by AlienRenders** [comment]
The LAS 1.4 header has an array of 15 64-bit integers storing the number of points for each record number 1 to 15. When using compatibility mode along with laszip_update_inventory() when writing out points, this extended array is not written to the file. I think only the first 5 are stored.

Basically, the laszip_close_writer() function is not aware of compatibility mode.

In laszip_dll.cpp at line 3309, there's this if statement:
if (laszip_dll->header.version_minor >= 4)

Well, in compatibility mode, you can never have version 1.4. It's always automatically reduced to 1.2 or 1.3 so the extended_number_of_points_by_return array is never written out.

**Comment by AlienRenders** [comment]
I decided to no longer use compatibility mode. This seems to work fine. Is LAS 1.4 fully supported now?

**Comment by rapidlasso** [comment]
Yes.

**Comment by AlienRenders** [comment]
There's still a bug with compatibility mode though.
