### ISSUE TITLE
LAZ 1.4 Spec/Reference

### ISSUE THREAD

**Issue by timodwhit** [LASzip/LASzip#77]
This might not be the best spot for this, but wanted to throw this out there since there was a brief discussion concerning "LAZ 1.4" spec and reference: https://github.com/copcio/copcio.github.io/pull/3/files#r687973879

The paper on laszip.org is from 2011 and there have been numerous releases to LASzip since then, and LAZ is a well known standard. Are there any plans to provide an updated spec or reference?

Again sorry if this is not the place, just want to make sure it is captured.

**Comment by timodwhit** [comment]
My apologies, just saw this: https://github.com/LASzip/LASzip/blob/master/design/ and thus it looks like it does exist already. 

@hobu and @abellgithub What components are missing to make this spec complete or non-reference-able for the end users of COPC? And could we get work to get them added or clarified?

**Comment by hobu** [comment]
Does https://github.com/LASzip/LASzip/tree/master/design actually match the current encoder? 

As for lack of a true specification, there have been a number of factors why that hasn't been done to date:

* The truest specification of the format is written in LGPL-licensed LASzip software. Most of its lifetime has seen only one software implementation, but now there are three.
* Ambiguity and uncertainty about the ASPRS LAS committee or OGC making overtures towards a compressed geospatial point cloud format.
* Lack of financial resources to fund @rapidlasso on the development of the document

**Comment by wiesehahn** [comment]
there is a specification since recently
https://rapidlasso.de/wp-content/uploads/2024/06/LAZ_Specification_1.4_R0.pdf

**Comment by rapidlasso** [comment]
Thanks @wiesehahn for the hint! The official Link to the spec is [https://downloads.rapidlasso.de/doc/LAZ_Specification_1.4_R0.pdf](https://downloads.rapidlasso.de/doc/LAZ_Specification_1.4_R0.pdf)
