### ISSUE TITLE
missing laszipper.cpp & lasunzipper.cpp => static lib

### ISSUE THREAD

**Issue by nxgraphics** [LASzip/LASzip#88]
Hi there,
while building with the static lib option, laszipper.cpp & lasunzipper.cpp files are not uncluded in the src's
so the static lib will be missing these definitions, is this the wanted behaviour ?
thx

plateform: windows
cmake: 3.25
ide: visual studio 2019

**Comment by rapidlasso** [comment]
yes. see changelog, e.g. laszip.hpp "25 February 2016 -- depreciating old libLAS laszipper/lasunzipper binding"
