### ISSUE TITLE
Any plan to release a new version?

### ISSUE THREAD

**Issue by hewenhao-hwh** [LASzip/LASzip#89]
Hello there,
I have noticed that a commit merged into master-branch two month ago. Do you have any plan to release a new stable version?
Thanks a lot!

**Comment by rapidlasso** [comment]
The current LASzip library is up to date. We support the LAS/LAZ format by 100% and I think it is the fastest LAS/LAZ supporting library.
The library is mantained by us, rapidlasso, the inventor of the LAZ format and the product owner of famous LAStools.
As soon there are changes in the LAS/LAZ format we will of course update and merge this library with LAStools and LASlib.
So about your question: A new stable version will be released as soon as we have to in terms of format changes.
