### ISSUE TITLE
Missing tag for 3.5.0

### ISSUE THREAD

**Issue by thbeu** [LASzip/LASzip#91]
Please add a tag for 3.5.0 (and edit release here on GitHub at your choice), such that we can better refer it in SBOM. Thanks. See https://github.com/LASzip/LASzip/issues/63#issuecomment-1338540538.

**Comment by rapidlasso** [comment]
created new tag

**Comment by dg0yt** [comment]
FTR I see a new [3.4.4](https://github.com/LASzip/LASzip/releases/tag/3.4.4), not 3.5.0.

**Comment by rapidlasso** [comment]
right. small changes get a small increment.

**Comment by dg0yt** [comment]
> right. small changes get a small increment.

I would agree. However it looks inconsistent now. 3.4.4 comes with API version 3.5.1.
https://github.com/LASzip/LASzip/blob/3.4.4/CMakeLists.txt#L11C1-L11C75

**Comment by thbeu** [comment]
OK, 3.4.4 reflects the license change.

**Comment by thbeu** [comment]
@rapidlasso Should the LASZIP_API_VERSION_STRING be set to 3.4.4 actually? It was changed in 8d82288effd827ee90bcb2f1f24cb3cc49026f5c from 3.4.3 to 3.5.0 to reflect the license change.

**Comment by thbeu** [comment]
Note, that Ubuntu 24.04 already packs a v3.5.0 which might lead to confusion with latest v3.4.4. @roehling
