### ISSUE TITLE
Installing laszip in ubuntu

### ISSUE THREAD

**Issue by asadclout** [LASzip/LASzip#93]
I run all these commands in terminal to install laszip.

git clone https://github.com/LASzip/LASzip.git
cd LASzip
cmake .
cmake --build 

after running these command when i write 
laszip --version 
it shows 
laszip command not found

basically i am trying to install laszip because it is prerequisite for "pylas" library of python

**Comment by thbeu** [comment]
Did you try `cmake --install`?

**Comment by rapidlasso** [comment]
LASzip and [LAStools](https://github.com/LAStools/LAStools) (including LASzip) is running within linux. Prebuild binaries are [available](https://rapidlasso.de/downloads/) as well.
