### ISSUE TITLE
Bug in commit 7a918c2

### ISSUE THREAD

**Issue by OgreTransporter** [LASzip/LASzip#97]
The file path of `laszip_api.h` has been changed
```
include/laszip/laszip_api.h → dll/laszip_api.h
```

but the CMake file has not been adapted:
https://github.com/LASzip/LASzip/blob/7dbc23c05b9e75e4280dd1ac117e4d7a90e88481/dll/CMakeLists.txt#L6

Fix:
```
LASZIP_ADD_INCLUDES("laszip" "${CMAKE_CURRENT_SOURCE_DIR}/laszip_api.h" ${LASZIP_API_VERSION_H})
```

**Comment by rapidlasso** [comment]
cmake fixed
